### ISSUE TITLE
system requirements list insufficient

### ISSUE THREAD

**Issue by mathog** [ebi-pf-team/interproscan#77]
On our Centos 6.9 system (64 bit) removed the old interproscan  5.27-66.0 and installed 5.30-69.0.  Big mistake.  The latter has binaries linked against much newer versions of the C, C++, etc. libraries than this system has.  So even though we have "Linux 64", which is listed as a requirement,  that is not sufficient.  Example:

```
ldd bin/nucleotide/getorf
bin/nucleotide/getorf: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by bin/nucleotide/getorf)
        linux-vdso.so.1 =>  (0x00007ffd291ee000)
        libm.so.6 => /lib64/libm.so.6 (0x00000037f5400000)
        libc.so.6 => /lib64/libc.so.6 (0x00000037f5000000)
        /lib64/ld-linux-x86-64.so.2 (0x000055a47fc5e000)
```
libc.so.6 on this system is 2.12.  The newer libraries  can be installed elsewhere on this system (so that they don't break existing programs), but it will be necessary to run ldd on all the binaries to figure out which set is needed.  (Seems like less work than recompiling it all from scratch.)  This computer already has copies of most of these programs (getorf, blastn, etc.) but it probably isn't safe to use them since who knows which version specific switches might be used.

**Comment by mathog** [comment]
That wasn't too bad.  Looking through all of interproscan/bin the only problem ones were in blast/ncbi-blast-2.6.0+, nucleotide, and sfld.  The rest of the binaries were linked against older libc and libstdc++.

1.  used rpsblast from a current NCBI rpm.  The current rpsbproc from the NCBI has the same linkage problems that the interproscan copy does.  Luckily an older one was found in a copy of interproscan-5.22-61.0 on another system, and that one was copied over.

2. nucleotide uses EMBOSS getorf.  We had that already.  Just removed the interproscan getorf binary and replaced it with a link to the working program.

3.  sfld has rebuild instructions under src.  It isn't necessary to make all of hmmer though.  We had downloaded the binary distribution and so never built the whole thing, and I didn't want to step on the binaries that were already there..  So went into the easel subdirectory and ran configure (made easel.h) and make (made libeasel.a).  After that sfld built with "make"..

**Comment by AGI-admin** [comment]
The instructions for sfld are insufficient as well.  Even after modifying the Makefile to point to our hmmer/easel data, there are errors compiling (see below).  I had to modify sfld_preprocess.c and sfld_postprocess.c with the suggestions of cc output, renaming ESLX_MSAFILE to ESL_MSAFILE, eslx_msafile_Open to esl_msafile_Open, etc.  Then it compiled and am able to run the binary.  Will see how it runs with data...

```
/opt/interproscan-5.31-70.0/src/sfld/1.1$ make
cc -I/usr/local/src/hmmer-3.2.1/easel -O2  -L/usr/local/src/hmmer-3.2.1/easel  sfld_preprocess.c  -leasel -lm -o sfld_preprocess
sfld_preprocess.c: In function ‘store_site_data’:
sfld_preprocess.c:109:5: error: unknown type name ‘ESLX_MSAFILE’; did you mean ‘ESL_MSAFILE’?
     ESLX_MSAFILE *msaf = NULL;
     ^~~~~~~~~~~~
     ESL_MSAFILE
sfld_preprocess.c:124:9: warning: implicit declaration of function ‘eslx_msafile_Open’; did you mean ‘esl_msafile_Open’? [-Wimplicit-function-declaration]
     if (eslx_msafile_Open(NULL, msa_fn, NULL, eslMSAFILE_STOCKHOLM, NULL, &msaf) != eslOK) {
         ^~~~~~~~~~~~~~~~~
         esl_msafile_Open
sfld_preprocess.c:140:18: warning: implicit declaration of function ‘eslx_msafile_Read’; did you mean ‘esl_msafile_Read’? [-Wimplicit-function-declaration]
     while ((rv = eslx_msafile_Read(msaf, &msa)) != eslEOF) {
                  ^~~~~~~~~~~~~~~~~
                  esl_msafile_Read
sfld_preprocess.c:163:5: warning: implicit declaration of function ‘eslx_msafile_Close’; did you mean ‘esl_msafile_Close’? [-Wimplicit-function-declaration]
     eslx_msafile_Close(msaf);
     ^~~~~~~~~~~~~~~~~~
     esl_msafile_Close
make: *** [<builtin>: sfld_preprocess] Error 1
```

**Comment by potter-s** [comment]
Have you tried HMMER version 3.1, as per the README? The sfld code should compile cleanly against that. Thanks for the note about only building the easel library.

**Comment by AGI-admin** [comment]
Yes it works with HMMER 3.1b2.  Sorry for the late reply.
